name: Formatting IDEA

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: AutoModality/action-clean@v1
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      #      - uses: engineerd/configurator@v0.0.8
      #        with:
      #          name: "intellij"
      #          url: "https://download.jetbrains.com/idea/ideaIU-2021.1.2.tar.gz"
      #          pathInArchive: "idea-IU-211.7442.40/bin/idea.sh"
      - name: Testing
        run: |
          mkdir ideafolder 
          wget -nv https://download.jetbrains.com/idea/ideaIC-2021.1.2.tar.gz -P ideafolder
          cd ideafolder
          tar -xzf ideaIC-2021.1.2.tar.gz
          rm -rf ideaIC-2021.1.2.tar.gz
          cd idea-IC-211.7442.40/bin
          ./idea.sh format ${{ github.workspace }}/Test.kt
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Format files" -a
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
