name: Formatting IDEA

on:
  pull_request:
    types: [ assigned, opened, synchronize, reopened, labeled ]

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #      - uses: engineerd/configurator@v0.0.8
      #        with:
      #          name: "intellij"
      #          url: "https://download.jetbrains.com/idea/ideaIU-2021.1.2.tar.gz"
      #          pathInArchive: "idea-IU-211.7442.40/bin/idea.sh"

      - name: Get changed files
        id: changed-files
        uses: jitterbit/get-changed-files@v1
      
      - name: List all added files
        run: |
          echo "${{ steps.files.outputs.all }}"
      - name: Cache Intellij
        id: intellij-idea
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/idea-IC-211.7442.40
          key: ${{ runner.os }}-idea-IC-211.7442.40
          
      - name: Download Intellij
        if: steps.intellij-idea.outputs.cache-hit != 'true'
        run: |
          wget -nv https://download.jetbrains.com/idea/ideaIC-2021.1.2.tar.gz
          tar -xzf ideaIC-2021.1.2.tar.gz
          rm -rf ideaIC-2021.1.2.tar.gz
          
      - name: Formatting
        run: |
          if [ -z "${{ steps.files.outputs.all }}" ]
          then
           echo "Nothing to format"
          elif [ -d "${{ github.workspace }}/idea-IC-211.7442.40" ]
          then
           echo "IDEA exists"
           idea_path="${{ github.workspace }}/idea-IC-211.7442.40/bin/idea.sh"
           ${{ github.workspace }}/idea-IC-211.7442.40/bin/idea.sh format ${{ steps.files.outputs.all }}
          else
           echo "IDEA not exists"
          fi
      - name: Commit files
        run: |
          # if [ -z "$(git diff --name-only HEAD)" ]
          # then
          #  echo "Nothing to format"
          # else
           git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
           git commit -m "Format files with IDEA" -a
          #fi
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
